"""Updated created_at columns in PostLike and CommentLike

Revision ID: 8bcaf1b6a3a7
Revises: 314be1a79444
Create Date: 2026-03-05 02:19:12.200674

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8bcaf1b6a3a7'
down_revision: Union[str, Sequence[str], None] = '314be1a79444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment_likes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('post_likes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post_likes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.alter_column('comment_likes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    # ### end Alembic commands ###
