"""change columns names

Revision ID: d21c810fefc8
Revises: 81747add7d4a
Create Date: 2026-02-16 20:43:25.965493

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd21c810fefc8'
down_revision: Union[str, Sequence[str], None] = '81747add7d4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('name', sa.String(length=50), nullable=False))
    op.add_column('items', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('items', sa.Column('tax', sa.Float(), nullable=True))
    op.create_index('name_index', 'items', ['name', 'id'], unique=False)
    op.drop_column('items', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index('name_index', table_name='items')
    op.drop_column('items', 'tax')
    op.drop_column('items', 'price')
    op.drop_column('items', 'name')
    # ### end Alembic commands ###
